### PR TITLE
Added P4 Python support to check out read-only file on save

### PR DESCRIPTION
**Pull request by Furash**
When using Perforce (P4) at work it is very likely to submit files and not be able to save them after due to read-only lock.
MACHIN3 tools Save Pie take over the ctrl+S hotkey, so I've added a little bit of logic to check out the file and put it to Default Changelist in P4.

image

### CODE REVIEW

**Comment by machin3io** [comment]
Hi Cyrill, I appreciate the effort you put into this.
But I can't merge this. I can't test it - not being on windows - and will have no use for it myself.

I understand the problem is solves is important for some people. Maybe a better solution would be to turn this into its own addon?
You could then use the save_pre handler to check in advance if the target location is a perforce repo and do the checkout accordingly. 
This would have the advantage that is works with MACHIN3tools, with native blender saving and any other way.

**Comment by Furash** [comment]
Great suggestion, I will look into this.

**Comment by Furash** [comment]
Sadly could be done only after this is implemented https://developer.blender.org/D11422 as pre_save handler is not triggered on read-only exception.

**Comment by Furash** [comment]
The problem is the exception is thrown before save_pre is triggered so I can't catch it with the save operator. The only way now is to implement a custom save operator which is not a great solution, because I want to use machin3 save pie. If they will add a handler that goes off sooner, then the issue would be gone. This would also be handy for people who use Git LFS locking at some point.

**Pull request closed without merging**
