### PR TITLE
Added Libraries Reload Button into Save Pie

### PR DESCRIPTION
**Pull request by TitusLVR**
Added this function, because standard ways are too many clicks and not working in some cases.
image
And this is a good extension for save pie i hope.

### CODE REVIEW

**Comment by machin3io** [comment]
Hey thanks. I'll take a look.
FWIW, I don't actually work in this public repo, I'm working in a private one and just push here when I release.
So I may close without merging and and still apply your changes.

**Comment by TitusLVR** [comment]
Yeah, close it, all good.

**Comment by machin3io** [comment]
So I'm going to add this now to 0.9. It's great, thank you very much. I haven't really worked with linked data in the past, but I will now!

**Comment by Gattung** [comment]
Very usefull!

**Pull request closed without merging**
